[tool.poetry]
name = "practical-python"
version = "0.1.0"
description = "Practical Python Programming (course by @dabeaz)"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
